'use strict';
// Extracts the NEARCADE PROBE SIM CORE region from src/scripts/viewer.js
// (verbatim, between the marker comments) into www/viewer-sim.js, which the
// probe loads to simulate the viewer side with the real production code.
// Run from the repo root: node tools/gamepad-probe/extract-sim.js
const fs = require('fs');
const path = require('path');

const viewerPath = path.join(__dirname, '..', '..', 'src', 'scripts', 'viewer.js');
const outPath = path.join(__dirname, 'www', 'viewer-sim.js');
const viewer = fs.readFileSync(viewerPath, 'utf8');

const START = '// ── NEARCADE PROBE SIM CORE: START ─';
const END = '// ── NEARCADE PROBE SIM CORE: END ─';

const parts = [];
let i = 0;
while (true) {
  const s = viewer.indexOf(START, i);
  if (s === -1) break;
  const e = viewer.indexOf(END, s);
  if (e === -1) throw new Error('Unterminated SIM CORE marker in ' + viewerPath);
  parts.push(viewer.slice(s, e).replace(/^\/\/ ── NEARCADE PROBE SIM CORE: START ─.+\n/, ''));
  i = e;
}
if (!parts.length) throw new Error('No SIM CORE markers found in ' + viewerPath);

const out = `'use strict';
// AUTO-GENERATED by tools/gamepad-probe/extract-sim.js from
// src/scripts/viewer.js (NEARCADE PROBE SIM CORE region) — DO NOT EDIT.
// Regenerate with: node tools/gamepad-probe/extract-sim.js
var calibMaps = {};
var smartDb = {};
var myId = 'probe';

${parts.join('\n\n')}

window.NearcadeSim = {
  getSafeGamepadId: getSafeGamepadId,
  lookupCalibMap: lookupCalibMap,
  applyCalibration: applyCalibration,
  applyGamepadDzSens: applyGamepadDzSens,
  packGamepadJson: _packGamepadJson
};
Object.defineProperty(window.NearcadeSim, 'smartDb', {
  get: function () { return smartDb; },
  set: function (v) { smartDb = v; },
  enumerable: true, configurable: true
});
Object.defineProperty(window.NearcadeSim, 'calibMaps', {
  get: function () { return calibMaps; },
  set: function (v) { calibMaps = v; },
  enumerable: true, configurable: true
});
`;
fs.writeFileSync(outPath, out);
console.log('extracted ' + parts.length + ' block(s) -> ' + outPath);
